# Generated by Django 5.1.1 on 2024-09-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_supervisor_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='user_generated_id',
        ),
    ]
