# Generated by Django 5.1.1 on 2024-09-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_user_id_customuser_user_generated_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedwork',
            name='project_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
