# Generated by Django 5.1.1 on 2024-09-06 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_submittedwork_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='students',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
