# Generated by Django 5.1.1 on 2024-09-06 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_supervisor_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised', to=settings.AUTH_USER_MODEL),
        ),
    ]
