# Generated by Django 5.1.1 on 2024-09-06 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_supervisor_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedwork',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submittedwork',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
