# Generated by Django 5.1.1 on 2024-09-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_user_submittedwork_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='students',
            new_name='student',
        ),
    ]
